---
title: "<div id=\"brand\">h|1i|0g|3h|2c|1h|2a|1r|3t|2e|1r|2{userchile}</div>"
author: "Joshua Kunst, Julio 2017"
output:
  revealjs::revealjs_presentation:
    self_contained: false
    mathjax: null
    transition: fade
    css: ["styles.css"]
    incremental: true
    center: false
    theme: simple
    fig_width: 5
    fig_height: 4
    reveal_options:
      slideNumber: true
      controls: false
      mouseWheel: false
---

# Quién soy y que haré(mos)? {.white .center data-background=#D32F2F}

```{r, include = FALSE}
knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)
source("setup.R")
```

## Quién soy

- De día hago como que trabajo en riesgo (70%)
- En Proyectos Personales (30%)
- Me gusta escribir código (en [R](https://cran.r-project.org/)!)
- Y compartirlo en [jkunst.com](http://jkunst.com)
- De casualidad soy Estadístico

## Que haré(mos)?

- Revisar un poco, solo un poco de historia
- Que es `highcharter`? Que es `highchartsJS`?
- Implementación del API de `highchartsJS` en `highcharter`
- Función genérica `hchart`
- Ejemplos simples, y quizás algunos más complejos.
- Si el tiempo da, integración con `shiny`, `rmarkdown`

# Historia  {.white .center data-background=#D32F2F}

## R base 

## Lattice

## ggplot2

## htmlwidgets

## Consideraciones

R es muy flexible lo que lleva a:

- Tener gran variedad de opciones `r ico("thumbs-o-up", "#337ab7")`
- Pero con la consideración de que cada paquete tiene su propia sintaxis `r ico("exclamation-triangle", "#d58512")`

# `highchartsJS` y `highcharter`, Que son? {.white .center data-background=#D32F2F}

# API de `highchartsJS` en R {.white .center data-background=#D32F2F}

# `hchart` al rescate {.white .center data-background=#D32F2F}

# Ejemplos :D {.white .center data-background=#D32F2F}

# Vamos a la consola? {.white .center data-background=#D32F2F}

# Gracias {.white .center data-background=#D32F2F}

## Gracias

> - Highcharter website:  https://github.com/jbkunst/highcharter
> - Presentación: http://jkunst.com/r-material/201707-highcharter-en-una-cascara-de-nuez/
> - Código: http://jkunst.com/r-material/201707-highcharter-en-una-cascara-de-nuez/code.html
> - Mah Blog: http://jkunst.com



