---
title: '<br><br>Data Viz desde un amateur<br><small>y lo aprendido en algunos años</small>
<link href="https://fonts.googleapis.com/css?family=Bangers|Roboto+Condensed|Kalam" rel="stylesheet">'
author: Joshua Kunst, Nov 16
output:
  revealjs::revealjs_presentation:
    mathjax: null
    transition: fade
    css: styles.css
    incremental: true
    center: false
    theme: simple
    fig_width: 7
    fig_height: 5
    reveal_options:
      slideNumber: true
      controls: false
      mouseWheel: false
---

# Quien creo ser {.section-title-white .center data-background="http://cliparts.co/cliparts/8cE/bkB/8cEbkByXi.jpg"}

## De dia, alguien normal {data-background="http://i.giphy.com/l2JHVUriDGEtWOx0c.gif"}

## De noche, hacker {.section-title-white data-background=#000 data-background-iframe="http://giphy.com/embed/YQitE4YNQNahy"}

## Nah

- Estadístico <span>Y un mix de cosas debido a la experiencia</span>
- Evangelizador de **R** <span>Oh sí!</span>
- Esporádicamente blogero <span>Cuando el tiempo da</span>
- Me gusta escribir `código` <span>Sep</span>
- Analizar y visualizar datos <span>Cuado la imaginación da</span>
- Compartir todo lo anterior <span>En forma de paquetes y demases</span>

# Que vengo a contar {.center}

## De mi workflow de <strike>trabajo</strike> vida {data-background="http://r4ds.had.co.nz/diagrams/data-science.png"}

## Recomendaciones subjetivas {data-background="https://www.r-project.org/logo/Rlogo.png"}

## Algunos post que he realizado {data-background="https://www.r-project.org/logo/Rlogo.png"}

# Workflow

- Para todo uso R. Incluso para 

## Recomendaciones

- Escribir código, por que sí, y también por que no. Así aumentamos el 
valor esperado de errores **detectados**. 

- 

## One-hit wonders


# TY


